################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Cabac.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264CodeFrame.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Denoise.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264EncApi.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Init.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Mad.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264NalUnit.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PictureBuffer.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PictureParameterSet.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PutBits.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264RateControl.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Sei.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264SequenceParameterSet.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Slice.c \
D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/h264encapi_ext.c 

OBJS += \
./Middlewares/VideoEncoder/H264/H264Cabac.o \
./Middlewares/VideoEncoder/H264/H264CodeFrame.o \
./Middlewares/VideoEncoder/H264/H264Denoise.o \
./Middlewares/VideoEncoder/H264/H264EncApi.o \
./Middlewares/VideoEncoder/H264/H264Init.o \
./Middlewares/VideoEncoder/H264/H264Mad.o \
./Middlewares/VideoEncoder/H264/H264NalUnit.o \
./Middlewares/VideoEncoder/H264/H264PictureBuffer.o \
./Middlewares/VideoEncoder/H264/H264PictureParameterSet.o \
./Middlewares/VideoEncoder/H264/H264PutBits.o \
./Middlewares/VideoEncoder/H264/H264RateControl.o \
./Middlewares/VideoEncoder/H264/H264Sei.o \
./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.o \
./Middlewares/VideoEncoder/H264/H264Slice.o \
./Middlewares/VideoEncoder/H264/h264encapi_ext.o 

C_DEPS += \
./Middlewares/VideoEncoder/H264/H264Cabac.d \
./Middlewares/VideoEncoder/H264/H264CodeFrame.d \
./Middlewares/VideoEncoder/H264/H264Denoise.d \
./Middlewares/VideoEncoder/H264/H264EncApi.d \
./Middlewares/VideoEncoder/H264/H264Init.d \
./Middlewares/VideoEncoder/H264/H264Mad.d \
./Middlewares/VideoEncoder/H264/H264NalUnit.d \
./Middlewares/VideoEncoder/H264/H264PictureBuffer.d \
./Middlewares/VideoEncoder/H264/H264PictureParameterSet.d \
./Middlewares/VideoEncoder/H264/H264PutBits.d \
./Middlewares/VideoEncoder/H264/H264RateControl.d \
./Middlewares/VideoEncoder/H264/H264Sei.d \
./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.d \
./Middlewares/VideoEncoder/H264/H264Slice.d \
./Middlewares/VideoEncoder/H264/h264encapi_ext.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/VideoEncoder/H264/H264Cabac.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Cabac.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264CodeFrame.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264CodeFrame.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264Denoise.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Denoise.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264EncApi.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264EncApi.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264Init.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Init.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264Mad.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Mad.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264NalUnit.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264NalUnit.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264PictureBuffer.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PictureBuffer.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264PictureParameterSet.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PictureParameterSet.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264PutBits.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264PutBits.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264RateControl.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264RateControl.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264Sei.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Sei.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264SequenceParameterSet.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264SequenceParameterSet.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/H264Slice.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/H264Slice.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/VideoEncoder/H264/h264encapi_ext.o: D:/____N6M/__OEM/Poly/VENC_RTSP_Server_with_PSRAM_2025_08_28_v1_0/VENC_RTSP_Server/Middlewares/Third_Party/VideoEncoder/source/h264/h264encapi_ext.c Middlewares/VideoEncoder/H264/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N6xx -DDEBUG -DSTM32 -DSTM32N657xx -DTX_SINGLE_MODE_SECURE -DETH_PHY_1000MBITS_SUPPORTED -DNX_INCLUDE_USER_DEFINE_FILE -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../../Appli/Core/Inc -I../../../Appli/AZURE_RTOS/App -I../../../Appli/NetXDuo/App -I../../../Appli/NetXDuo/Target -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../Drivers/BSP/STM32N6570-DK -I../../../Drivers/BSP/Components/Common -I../../../Drivers/BSP/Components/imx335 -I../../../Drivers/BSP/Components/rtl8211 -I../../../Drivers/BSP/Components/aps256xx -I../../../Middlewares/ST/STM32_ISP_Library/isp/Inc -I../../../Middlewares/ST/STM32_ISP_Library/evision/Inc -I../../../Middlewares/ST/threadx/common/inc -I../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../Middlewares/ST/netxduo/addons/dhcp -I../../../Middlewares/ST/netxduo/addons/rtp -I../../../Middlewares/ST/netxduo/addons/rtsp -I../../../Middlewares/ST/netxduo/tsn/inc -I../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../Middlewares/ST/netxduo/common/inc -I../../../Middlewares/ST/VideoEncoder_EWL -I../../../Middlewares/Third_Party/VideoEncoder/source/common -I../../../Middlewares/Third_Party/VideoEncoder/inc -I../../../Middlewares/Third_Party/VideoEncoder/source/h264 -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-VideoEncoder-2f-H264

clean-Middlewares-2f-VideoEncoder-2f-H264:
	-$(RM) ./Middlewares/VideoEncoder/H264/H264Cabac.cyclo ./Middlewares/VideoEncoder/H264/H264Cabac.d ./Middlewares/VideoEncoder/H264/H264Cabac.o ./Middlewares/VideoEncoder/H264/H264Cabac.su ./Middlewares/VideoEncoder/H264/H264CodeFrame.cyclo ./Middlewares/VideoEncoder/H264/H264CodeFrame.d ./Middlewares/VideoEncoder/H264/H264CodeFrame.o ./Middlewares/VideoEncoder/H264/H264CodeFrame.su ./Middlewares/VideoEncoder/H264/H264Denoise.cyclo ./Middlewares/VideoEncoder/H264/H264Denoise.d ./Middlewares/VideoEncoder/H264/H264Denoise.o ./Middlewares/VideoEncoder/H264/H264Denoise.su ./Middlewares/VideoEncoder/H264/H264EncApi.cyclo ./Middlewares/VideoEncoder/H264/H264EncApi.d ./Middlewares/VideoEncoder/H264/H264EncApi.o ./Middlewares/VideoEncoder/H264/H264EncApi.su ./Middlewares/VideoEncoder/H264/H264Init.cyclo ./Middlewares/VideoEncoder/H264/H264Init.d ./Middlewares/VideoEncoder/H264/H264Init.o ./Middlewares/VideoEncoder/H264/H264Init.su ./Middlewares/VideoEncoder/H264/H264Mad.cyclo ./Middlewares/VideoEncoder/H264/H264Mad.d ./Middlewares/VideoEncoder/H264/H264Mad.o ./Middlewares/VideoEncoder/H264/H264Mad.su ./Middlewares/VideoEncoder/H264/H264NalUnit.cyclo ./Middlewares/VideoEncoder/H264/H264NalUnit.d ./Middlewares/VideoEncoder/H264/H264NalUnit.o ./Middlewares/VideoEncoder/H264/H264NalUnit.su ./Middlewares/VideoEncoder/H264/H264PictureBuffer.cyclo ./Middlewares/VideoEncoder/H264/H264PictureBuffer.d ./Middlewares/VideoEncoder/H264/H264PictureBuffer.o ./Middlewares/VideoEncoder/H264/H264PictureBuffer.su ./Middlewares/VideoEncoder/H264/H264PictureParameterSet.cyclo ./Middlewares/VideoEncoder/H264/H264PictureParameterSet.d ./Middlewares/VideoEncoder/H264/H264PictureParameterSet.o ./Middlewares/VideoEncoder/H264/H264PictureParameterSet.su ./Middlewares/VideoEncoder/H264/H264PutBits.cyclo ./Middlewares/VideoEncoder/H264/H264PutBits.d ./Middlewares/VideoEncoder/H264/H264PutBits.o ./Middlewares/VideoEncoder/H264/H264PutBits.su ./Middlewares/VideoEncoder/H264/H264RateControl.cyclo ./Middlewares/VideoEncoder/H264/H264RateControl.d ./Middlewares/VideoEncoder/H264/H264RateControl.o ./Middlewares/VideoEncoder/H264/H264RateControl.su ./Middlewares/VideoEncoder/H264/H264Sei.cyclo ./Middlewares/VideoEncoder/H264/H264Sei.d ./Middlewares/VideoEncoder/H264/H264Sei.o ./Middlewares/VideoEncoder/H264/H264Sei.su ./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.cyclo ./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.d ./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.o ./Middlewares/VideoEncoder/H264/H264SequenceParameterSet.su ./Middlewares/VideoEncoder/H264/H264Slice.cyclo ./Middlewares/VideoEncoder/H264/H264Slice.d ./Middlewares/VideoEncoder/H264/H264Slice.o ./Middlewares/VideoEncoder/H264/H264Slice.su ./Middlewares/VideoEncoder/H264/h264encapi_ext.cyclo ./Middlewares/VideoEncoder/H264/h264encapi_ext.d ./Middlewares/VideoEncoder/H264/h264encapi_ext.o ./Middlewares/VideoEncoder/H264/h264encapi_ext.su

.PHONY: clean-Middlewares-2f-VideoEncoder-2f-H264

